### ISSUE TITLE
Add jdk.management

### ISSUE THREAD

**Issue by vladfrangu** [Prouser123/minecraft-runner-docker#4]
Stacktrace for ref:
```
[15:28:28 WARN]: java.lang.reflect.UndeclaredThrowableException
[15:28:28 WARN]:        at com.sun.proxy.$Proxy54.dumpHeap(Unknown Source)
[15:28:28 WARN]:        at me.lucko.spark.common.heapdump.HeapDump.dumpHeap(HeapDump.java:59)
[15:28:28 WARN]:        at me.lucko.spark.common.command.modules.MemoryModule.lambda$null$5(MemoryModule.java:127)
[15:28:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[15:28:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[15:28:28 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:28:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:28:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:28:28 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[15:28:28 WARN]: Caused by: javax.management.InstanceNotFoundException: com.sun.management:type=HotSpotDiagnostic
[15:28:28 WARN]:        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(Unknown Source)
[15:28:28 WARN]:        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
[15:28:28 WARN]:        at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
[15:28:28 WARN]:        at java.management/com.sun.jmx.mbeanserver.MXBeanProxy$InvokeHandler.invoke(Unknown Source)
[15:28:28 WARN]:        at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(Unknown Source)
[15:28:28 WARN]:        at java.management/javax.management.MBeanServerInvocationHandler.invoke(Unknown Source)
[15:28:28 WARN]:        ... 9 more
```

**Comment by jcxldn** [comment]
Added in `7ecaa3e`.
